# Generated by Django 5.1.5 on 2025-02-03 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleColorGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_date', models.DateField(auto_now_add=True)),
                ('guessed_color', models.CharField(choices=[('red', 'قرمز'), ('green', 'سبز')], max_length=5)),
                ('guess_time', models.TimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'guess_date')},
            },
        ),
        migrations.CreateModel(
            name='CandlePriceGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_date', models.DateField(auto_now_add=True)),
                ('guessed_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guess_time', models.TimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'guess_date')},
            },
        ),
    ]
